[package]
name = "echor"
version = "0.1.0"
edition = "2021"
authors = [ "Shunsuke Ishii" ]

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "2"